kind: pipeline
name: default

steps:
- name: test
  image: golang
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
    - ls
    - pwd
    - ls
    - echo $USERNAME
    - echo $PASSWORD
