kind: pipeline
name: default

steps:
- name: master
  image: golang
  environment:
    USERNAME:
      from_secret: username
    PASSWORD:
      from_secret: password
  commands:
    - echo master
    - echo $USERNAME
    - echo $PASSWORD
  services:
  - name: redis
    image: redis


